FROM minimsecure/circleci-openwrt-builder:base

WORKDIR /workdir
COPY . builder
RUN chown -R openwrt: /workdir

USER openwrt

RUN make -C /workdir/builder linksys-wrt1900acs.sdk

RUN make -C /workdir/builder linksys-wrt1900acs.toolchain

CMD make -C /workdir/builder linksys-wrt1900acs
