version: 2.1

jobs:
  build-image:
    description: Build and publish a Docker image for a supported platform
    parameters:
      target_name:
        description: Target architecture
        type: string
    machine: true
    steps:
      - checkout
      - run:
          name: Build image for << parameters.target_name >>
          command: |
            docker image build --build-arg "platform=<< parameters.target_name >>" --tag minimsecure/openwrt-builder:<< parameters.target_name >> .
            mkdir -p out
            docker image save -o out/<< parameters.target_name >>.dockerimg minimsecure/openwrt-builder:<< parameters.target_name >>
      - run:
          name: Publish image to dockerhub
          command: |
            if [[ -z "$DOCKER_USER" ]] || [[ -z "$DOCKER_PASS" ]]; then
              echo "docker credentials unset, skipping upload"
            else
              echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
              docker push "minimsecure/openwrt-builder:<< parameters.target_name >>"
            fi
      - store_artifacts:
          path: out
          destination: build

  build-artifacts:
    description: Builds binary OpenWrt packages using the images hosted on Docker Hub
    parameters:
      target_name:
        description: Target architecture
        type: string
    docker:
      - image: minimsecure/openwrt-builder:<< parameters.target_name >>
    working_directory: /builder
    steps:
      - run:
          name: Build firmware and packages for << parameters.target_name >>
          command: make << parameters.target_name >>
      - store_artifacts:
          path: build/out
          destination: build

workflows:
  version: 2
  build-all:
    jobs:
      # Build and publish a new Docker image for each target platform
      - build-image:
          name: build-ar71xx
          target_name: ar71xx
          filters:
            tags:
              only: /^.*/
      - build-image:
          name: build-ipq40xx
          target_name: ipq40xx
          filters:
            tags:
              only: /^.*/
      - build-image:
          name: build-mvebu-cortexa9
          target_name: mvebu-cortexa9
          filters:
            tags:
              only: /^.*/

      # Build artifacts jobs that produce binary OpenWrt images and packages
      - build-artifacts:
          name: artifacts-ar71xx
          requires:
            - build-ar71xx
          target_name: ar71xx
          filters:
            tags:
              only: /^.*/
            branches:
              only: master
      - build-artifacts:
          name: artifacts-ipq40xx
          requires:
            - build-ipq40xx
          target_name: ipq40xx
          filters:
            tags:
              only: /^.*/
            branches:
              only: master
      - build-artifacts:
          name: artifacts-mvebu-cortexa9
          requires:
            - build-mvebu-cortexa9
          target_name: mvebu-cortexa9
          filters:
            tags:
              only: /^.*/
            branches:
              only: master
