version: 2.1

jobs:
  build-image:
    description: Build and publish a Docker image for a supported platform
    parameters:
      target_name:
        description: Target architecture
        type: enum
        enum: ["base", "ar71xx", "ipq40xx", "mvebu-cortexa9"]
    machine: true
    steps:
      - checkout
      - run:
          name: Build image for << parameters.target_name >>
          command: |
            docker image build --file Dockerfile.<< parameters.target_name >> --tag minimsecure/circleci-openwrt-builder:<< parameters.target_name >> .
            mkdir -p out
            docker image save -o out/<< parameters.target_name >>.dockerimg minimsecure/circleci-openwrt-builder:<< parameters.target_name >>
      - run:
          name: Publish image to dockerhub
          command: |
            if [[ -z "$DOCKER_USER" ]] || [[ -z "$DOCKER_PASS" ]]; then
              echo "docker credentials unset, skipping upload"
            else
              echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
              docker push "minimsecure/circleci-openwrt-builder:<< parameters.target_name >>"
            fi
      - store_artifacts:
          path: out
          destination: out

  build-artifacts:
    description: Builds binary OpenWrt packages using the images hosted on Docker Hub
    parameters:
      target_name:
        description: Target architecture
        type: enum
        enum: ["ar71xx", "ipq40xx", "mvebu-cortexa9"]
    docker:
      - image: minimsecure/circleci-openwrt-builder:<< parameters.target_name >>
    working_directory: /workdir/builder
    steps:
      - store_artifacts:
          path: build/out
          destination: out

workflows:
  version: 2
  build-all:
    jobs:
      # Build and publish the base Docker image for all target platforms.
      - build-image:
          name: build-base
          target_name: base
          filters:
            tags:
              only: /^.*/

      # Build and publish a new Docker image for each target platform
      - build-image:
          name: build-ar71xx
          target_name: ar71xx
          requires:
            - build-base
          filters:
            tags:
              only: /^.*/
      - build-image:
          name: build-ipq40xx
          target_name: ipq40xx
          requires:
            - build-base
          filters:
            tags:
              only: /^.*/
      - build-image:
          name: build-mvebu-cortexa9
          target_name: mvebu-cortexa9
          requires:
            - build-base
          filters:
            tags:
              only: /^.*/

      # Build artifacts jobs that produce binary OpenWrt images and packages
      - build-artifacts:
          requires:
            - build-ar71xx
          target_name: ar71xx
          filters:
            tags:
              only: /^.*/
            branches:
              only: master
      - build-artifacts:
          requires:
            - build-ipq40xx
          target_name: ipq40xx
          filters:
            tags:
              only: /^.*/
            branches:
              only: master
      - build-artifacts:
          requires:
            - build-mvebu-cortexa9
          target_name: mvebu-cortexa9
          filters:
            tags:
              only: /^.*/
            branches:
              only: master
