version: 2.1

commands:
  build_image:
    description: Build an image using one of the Dockerfiles
    parameters:
      target_name:
        description: Target name for the image
        type: string
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Load previously built base image
          command: |
            if [[ "<< target_name >>" == "base" ]]; then
              echo "Building base image, not bothering with trying to load it. Skipping"
              exit 0
            fi
            docker image load -i out/base.dockerimg
      - run:
          name: Build image for << target_name >>
          command: |
            docker image build --file Dockerfile.<< target_name >> --tag minimsecure/circleci-openwrt-builder:<< target_name >> .
            mkdir -p out
            docker image save -o out/<< target_name >>.dockerimg minimsecure/circleci-openwrt-builder:<< target_name >>
      - store_artifacts:
          path: out
          destination: out
      - persist_to_workspace:
          root: .
          paths:
            - out/*.dockerimg

jobs:
  build-base:
    machine: true
    steps:
      - build_image:
          target_name: base
  build-gl_b1300:
    machine: true
    steps:
      - build_image:
          target_name: gl_b1300

workflows:
  version: 2
  build-all:
    jobs:
      - build-base
      - build-gl_b1300:
          requires:
            - build-base

# TODO:
# - add publish job