version: 2.1

commands:
  build_image:
    description: Build an image using one of the Dockerfiles
    parameters:
      target_name:
        description: Target name for the image
        type: enum
        enum: ["base", "ar71xx", "ipq40xx", "mvebu-cortexa9"]
    steps:
      - checkout
      - run:
          name: Build image for << parameters.target_name >>
          command: |
            docker image build --file Dockerfile.<< parameters.target_name >> --tag minimsecure/circleci-openwrt-builder:<< parameters.target_name >> .
            mkdir -p out
            docker image save -o out/<< parameters.target_name >>.dockerimg minimsecure/circleci-openwrt-builder:<< parameters.target_name >>
      - run:
          name: Publish image to dockerhub
          command: |
            if [[ -z "$DOCKER_USER" ]] || [[ -z "$DOCKER_PASS" ]]; then
              echo "docker credentials unset, skipping upload"
            else
              echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
              docker push "minimsecure/circleci-openwrt-builder:<< parameters.target_name >>"
            fi
      - store_artifacts:
          path: out
          destination: out

jobs:
  build-base:
    machine: true
    steps:
      - build_image:
          target_name: base
  build-ar71xx:
    machine: true
    steps:
      - build_image:
          target_name: ar71xx
  build-ipq40xx:
    machine: true
    steps:
      - build_image:
          target_name: ipq40xx
  build-mvebu-cortexa9:
    machine: true
    steps:
      - build_image:
          target_name: mvebu-cortexa9

workflows:
  version: 2
  build-all:
    jobs:
      - build-base:
          filters:
            tags:
              only: /^.*/
            branches:
              only: master
      - build-ar71xx:
          requires:
            - build-base
          filters:
            tags:
              only: /^.*/
      - build-ipq40xx:
          requires:
            - build-base
          filters:
            tags:
              only: /^.*/
      - build-mvebu-cortexa9:
          requires:
            - build-base
          filters:
            tags:
              only: /^.*/
