version: 2.1

commands:
  build_image:
    description: Build an image using one of the Dockerfiles
    parameters:
      target_name:
        description: Target name for the image
        type: enum
        enum: ["base", "archer_c7_v2", "archer_c7_v4", "gl_b1300", "gl_ar300m", "linksys-wrt1900acs"]
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Load previously built base image
          command: |
            if [[ "<< parameters.target_name >>" == "base" ]]; then
              echo "Building base image, not bothering with trying to load it. Skipping"
            else
              docker image load -i out/base.dockerimg
            fi
      - run:
          name: Build image for << parameters.target_name >>
          command: |
            docker image build --file Dockerfile.<< parameters.target_name >> --tag minimsecure/circleci-openwrt-builder:<< parameters.target_name >> .
            mkdir -p out
            docker image save -o out/<< parameters.target_name >>.dockerimg minimsecure/circleci-openwrt-builder:<< parameters.target_name >>
      - store_artifacts:
          path: out
          destination: out
      - persist_to_workspace:
          root: .
          paths:
            - out/<< parameters.target_name >>.dockerimg

jobs:
  build-base:
    machine: true
    steps:
      - build_image:
          target_name: base
  build-archer_c7_v2:
    machine: true
    steps:
      - build_image:
          target_name: archer_c7_v2
  build-archer_c7_v4:
    machine: true
    steps:
      - build_image:
          target_name: archer_c7_v4
  build-gl_b1300:
    machine: true
    steps:
      - build_image:
          target_name: gl_b1300
  build-gl_ar300m:
    machine: true
    steps:
      - build_image:
          target_name: gl_ar300m
  build-linksys-wrt1900acs:
    machine: true
    steps:
      - build_image:
          target_name: linksys-wrt1900acs
  publish-images:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Load newly built images
          command: |
            for img in out/*.dockerimg; do
              docker image load -i $img
            done
      - run:
          name: Publish images to dockerhub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push "minimsecure/circleci-openwrt-builder:base"
            docker push "minimsecure/circleci-openwrt-builder:archer_c7_v2"
            docker push "minimsecure/circleci-openwrt-builder:archer_c7_v4"
            docker push "minimsecure/circleci-openwrt-builder:gl_b1300"
            docker push "minimsecure/circleci-openwrt-builder:gl_ar300m"
            docker push "minimsecure/circleci-openwrt-builder:linksys-wrt1900acs"

workflows:
  version: 2
  build-all:
    jobs:
      - build-base:
          filters:
            tags:
              only: /^.*/
      - build-archer_c7_v2:
          requires:
            - build-base
          filters:
            tags:
              only: /^.*/
      - build-archer_c7_v4:
          requires:
            - build-base
          filters:
            tags:
              only: /^.*/
      - build-gl_b1300:
          requires:
            - build-base
          filters:
            tags:
              only: /^.*/
      - build-gl_ar300m:
          requires:
            - build-base
          filters:
            tags:
              only: /^.*/
      - build-linksys-wrt1900acs:
          requires:
            - build-base
          filters:
            tags:
              only: /^.*/
      - publish-images:
          requires:
            - build-base
            - build-archer_c7_v2
            - build-archer_c7_v4
            - build-gl_b1300
            - build-gl_ar300m
            - build-linksys-wrt1900acs
          filters:
            branches:
              only: master
