version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build base image
          command: |
            docker image build --file Dockerfile.base --tag minimsecure/circleci-openwrt-builder:base .
            mkdir -p out
            docker image save -o out/base.dockerimg minimsecure/circleci-openwrt-builder:base
      - run:
          name: Build SDK GL.iNet GL-B1300
          command: |
            docker image build --file Dockerfile.gl_b1300 --tag minimsecure/circleci-openwrt-builder:gl_b1300 .
            mkdir -p out
            docker image save -o out/gl_b1300.dockerimg minimsecure/circleci-openwrt-builder:gl_b1300
      - store_artifacts:
          path: out
          destination: out

# TODO:
# - separate jobs for each image + workflow to orchestrate things
# - use a function instead of repeating everything above
# - add publish job